<a href="https://colab.research.google.com/github/FariyaAhmedosd/Google_colab_practice/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

2.2.3

In [ ]:
df=pd.read_csv("/content/annual-enterprise-survey-2025-financial-year-provisional.csv")

In [ ]:
print(df)

       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2025                     Level 1                99999
1      2025                     Level 1                99999
2      2025                     Level 1                99999
3      2025                     Level 1                99999
4      2025                     Level 1                99999
...     ...                         ...                  ...
60250  2013                     Level 3                 ZZ11
60251  2013                     Level 3                 ZZ11
60252  2013                     Level 3                 ZZ11
60253  2013                     Level 3                 ZZ11
60254  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
60250  Food product manufacturing          Percentage           H37
60251  Food product manufacturing          Percentage           H38
60252  Food product manufacturing          Percentage           H39
60253  Food product manufacturing          Percentage           H40
60254  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
60250                                      Quick ratio       Financial ratios
60251              Margin on sales of goods for resale       Financial ratios
60252                                 Return on equity       Financial ratios
60253                           Return on total assets       Financial ratios
60254                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      976077  ANZSIC06 divisions A-S (excluding classes K633...
1      854561  ANZSIC06 divisions A-S (excluding classes K633...
2       96238  ANZSIC06 divisions A-S (excluding classes K633...
3       25279  ANZSIC06 divisions A-S (excluding classes K633...
4      867750  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
60250      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
60251      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
60252      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
60253       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
60254      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[60255 rows x 10 columns]

In [ ]:
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...

In [ ]:
df.tail()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
60250,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60251,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60252,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60253,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
60254,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [ ]:
df.head(50)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2025,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,976077,ANZSIC06 divisions A-S (excluding classes K633...
1,2025,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,854561,ANZSIC06 divisions A-S (excluding classes K633...
2,2025,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,96238,ANZSIC06 divisions A-S (excluding classes K633...
3,2025,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25279,ANZSIC06 divisions A-S (excluding classes K633...
4,2025,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,867750,ANZSIC06 divisions A-S (excluding classes K633...
5,2025,Level 1,99999,All industries,Dollars (millions),H09,Interest and donations,Financial performance,67376,ANZSIC06 divisions A-S (excluding classes K633...
6,2025,Level 1,99999,All industries,Dollars (millions),H10,Indirect taxes,Financial performance,9483,ANZSIC06 divisions A-S (excluding classes K633...
7,2025,Level 1,99999,All industries,Dollars (millions),H11,Depreciation,Financial performance,33337,ANZSIC06 divisions A-S (excluding classes K633...
8,2025,Level 1,99999,All industries,Dollars (millions),H12,Salaries and wages paid,Financial performance,160833,ANZSIC06 divisions A-S (excluding classes K633...
9,2025,Level 1,99999,All industries,Dollars (millions),H13,Redundancy and severance,Financial performance,455,ANZSIC06 divisions A-S (excluding classes K633...
10,2025,Level 1,99999,All industries,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,1702,ANZSIC06 divisions A-S (excluding classes K633...
11,2025,Level 1,99999,All industries,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,578315,ANZSIC06 divisions A-S (excluding classes K633...
12,2025,Level 1,99999,All industries,Dollars (millions),H20,Non-operating expenses,Financial performance,16703,ANZSIC06 divisions A-S (excluding classes K633...
13,2025,Level 1,99999,All industries,Dollars (millions),H21,Opening stocks,Financial performance,86693,ANZSIC06 divisions A-S (excluding classes K633...
14,2025,Level 1,99999,All industries,Dollars (millions),H22,Closing stocks,Financial performance,88214,ANZSIC06 divisions A-S (excluding classes K633...
15,2025,Level 1,99999,All industries,Dollars (millions),H23,Surplus before income tax,Financial performance,109848,ANZSIC06 divisions A-S (excluding classes K633...
16,2025,Level 1,99999,All industries,Dollars (millions),H24,Total assets,Financial position,3068548,ANZSIC06 divisions A-S (excluding classes K633...
17,2025,Level 1,99999,All industries,Dollars (millions),H25,Current assets,Financial position,932824,ANZSIC06 divisions A-S (excluding classes K633...
18,2025,Level 1,99999,All industries,Dollars (millions),H26,Fixed tangible assets,Financial position,774041,ANZSIC06 divisions A-S (excluding classes K633...
19,2025,Level 1,99999,All industries,Dollars (millions),H29,Other assets,Financial position,1361682,ANZSIC06 divisions A-S (excluding classes K633...
20,2025,Level 1,99999,All industries,Dollars (millions),H30,Total equity and liabilities,Financial position,3068548,ANZSIC06 divisions A-S (excluding classes K633...
21,2025,Level 1,99999,All industries,Dollars (millions),H31,Shareholders funds or owners equity,Financial position,1064513,ANZSIC06 divisions A-S (excluding classes K633...
22,2025,Level 1,99999,All industries,Dollars (millions),H32,Current liabilities,Financial position,1185025,ANZSIC06 divisions A-S (excluding classes K633...
23,2025,Level 1,99999,All industries,Dollars (millions),H33,Other liabilities,Financial position,819010,ANZSIC06 divisions A-S (excluding classes K633...
24,2025,Level 1,99999,All industries,Dollars,H34,Total income per employee count,Financial ratios,488300,ANZSIC06 divisions A-S (excluding classes K633...
25,2025,Level 1,99999,All industries,Dollars,H35,Surplus per employee count,Financial ratios,55000,ANZSIC06 divisions A-S (excluding classes K633...
26,2025,Level 1,99999,All industries,Percentage,H36,Current ratio,Financial ratios,79,ANZSIC06 divisions A-S (excluding classes K633...
27,2025,Level 1,99999,All industries,Percentage,H37,Quick ratio,Financial ratios,71,ANZSIC06 divisions A-S (excluding classes K633...
28,2025,Level 1,99999,All industries,Percentage,H39,Return on equity,Financial ratios,10,ANZSIC06 divisions A-S (excluding classes K633...
29,2025,Level 1,99999,All industries,Percentage,H40,Return on total assets,Financial ratios,4,ANZSIC06 divisions A-S (excluding classes K633...
30,2025,Level 1,99999,All industries,Percentage,H41,Liabilities structure,Financial ratios,35,ANZSIC06 divisions A-S (excluding classes K633...
31,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H01,Total income,Financial performance,60188,ANZSIC06 division A
32,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H04,Sales of goods and services,Financial performance,56366,ANZSIC06 division A
33,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H05,"Interest, dividends and donations",Financial performance,1409,ANZSIC06 division A
34,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H06,"Government funding, grants and subsidies",Financial performance,27,ANZSIC06 division A
35,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H07,Non-operating income,Financial performance,2385,ANZSIC06 division A
36,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H08,Total expenditure,Financial performance,52291,ANZSIC06 division A
37,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H09,Interest and donations,Financial performance,4485,ANZSIC06 division A
38,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H10,Indirect taxes,Financial performance,599,ANZSIC06 division A
39,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H11,Depreciation,Financial performance,2739,ANZSIC06 division A
40,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H12,Salaries and wages paid,Financial performance,7638,ANZSIC06 division A
41,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H13,Redundancy and severance,Financial performance,10,ANZSIC06 division A
42,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H19,Purchases and other operating expenses,Financial performance,35345,ANZSIC06 division A
43,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H20,Non-operating expenses,Financial performance,1484,ANZSIC06 division A
44,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H21,Opening stocks,Financial performance,16033,ANZSIC06 division A
45,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H22,Closing stocks,Financial performance,16797,ANZSIC06 division A
46,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H23,Surplus before income tax,Financial performance,8662,ANZSIC06 division A
47,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H24,Total assets,Financial position,231310,ANZSIC06 division A
48,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H25,Current assets,Financial position,42939,ANZSIC06 division A
49,2025,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H26,Fixed tangible assets,Financial position,130974,ANZSIC06 division A

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60255 entries, 0 to 60254
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         60255 non-null  int64
 1   Industry_aggregation_NZSIOC  60255 non-null  object
 2   Industry_code_NZSIOC         60255 non-null  object
 3   Industry_name_NZSIOC         60255 non-null  object
 4   Units                        60255 non-null  object
 5   Variable_code                60255 non-null  object
 6   Variable_name                60255 non-null  object
 7   Variable_category            60255 non-null  object
 8   Value                        60255 non-null  object
 9   Industry_code_ANZSIC06       60255 non-null  object
dtypes: int64(1), object(9)
memory usage: 4.6+ MB

In [ ]:
df.describe()

               Year
count  60255.000000
mean    2019.000000
std        3.741688
min     2013.000000
25%     2016.000000
50%     2019.000000
75%     2022.000000
max     2025.000000

In [ ]:
df.shape

(60255, 10)

In [ ]:
print(df.min())

Year                                                2013
Industry_aggregation_NZSIOC                      Level 1
Industry_code_NZSIOC                               99999
Industry_name_NZSIOC                       Accommodation
Units                                            Dollars
Variable_code                                        H01
Variable_name                  Additions to fixed assets
Variable_category                  Financial performance
Value                                                 -1
Industry_code_ANZSIC06               ANZSIC06 Group F380
dtype: object

In [ ]:
df.iloc[-2]

Date;Open;High;Low;Close;Volume    2026.01.30 23:30;4874.12;4881.29;4849.12;4860....
Name: 494233, dtype: object

In [ ]:
df=pd.read_csv("/content/wholesale-trade-survey-june-2026-quarter.zip")

In [ ]:
print(df)

     Series_reference   Period  Data_value  Suppressed STATUS    UNITS  \
0         WTSQ.SFA1CA  1995.03    2368.690         NaN      F  Dollars
1         WTSQ.SFA1CA  1995.06    2100.440         NaN      F  Dollars
2         WTSQ.SFA1CA  1995.09    2070.210         NaN      F  Dollars
3         WTSQ.SFA1CA  1995.12    2284.770         NaN      F  Dollars
4         WTSQ.SFA1CA  1996.03    2134.760         NaN      F  Dollars
...               ...      ...         ...         ...    ...      ...
5781      WTSQ.SFZ9CT  2025.06   18026.490         NaN      R  Dollars
5782      WTSQ.SFZ9CT  2025.09   17885.529         NaN      R  Dollars
5783      WTSQ.SFZ9CT  2025.12   17842.642         NaN      R  Dollars
5784      WTSQ.SFZ9CT  2026.03   18406.127         NaN      R  Dollars
5785      WTSQ.SFZ9CT  2026.06   19255.759         NaN      F  Dollars

      Magnitude                       Subject  \
0             6  Wholesale Trade Survey - WTS
1             6  Wholesale Trade Survey - WTS
2             6  Wholesale Trade Survey - WTS
3             6  Wholesale Trade Survey - WTS
4             6  Wholesale Trade Survey - WTS
...         ...                           ...
5781          6  Wholesale Trade Survey - WTS
5782          6  Wholesale Trade Survey - WTS
5783          6  Wholesale Trade Survey - WTS
5784          6  Wholesale Trade Survey - WTS
5785          6  Wholesale Trade Survey - WTS

                                                  Group  \
0     Industry by variable - (ANZSIC06) - Subannual ...
1     Industry by variable - (ANZSIC06) - Subannual ...
2     Industry by variable - (ANZSIC06) - Subannual ...
3     Industry by variable - (ANZSIC06) - Subannual ...
4     Industry by variable - (ANZSIC06) - Subannual ...
...                                                 ...
5781  Industry by variable - (ANZSIC06) - Subannual ...
5782  Industry by variable - (ANZSIC06) - Subannual ...
5783  Industry by variable - (ANZSIC06) - Subannual ...
5784  Industry by variable - (ANZSIC06) - Subannual ...
5785  Industry by variable - (ANZSIC06) - Subannual ...

                  Series_title_1            Series_title_2  Series_title_3  \
0     Basic material wholesaling  Sales (operating income)  Current prices
1     Basic material wholesaling  Sales (operating income)  Current prices
2     Basic material wholesaling  Sales (operating income)  Current prices
3     Basic material wholesaling  Sales (operating income)  Current prices
4     Basic material wholesaling  Sales (operating income)  Current prices
...                          ...                       ...             ...
5781           Total wholesaling              Total stocks  Current prices
5782           Total wholesaling              Total stocks  Current prices
5783           Total wholesaling              Total stocks  Current prices
5784           Total wholesaling              Total stocks  Current prices
5785           Total wholesaling              Total stocks  Current prices

     Series_title_4 Series_title_5
0        Unadjusted            NaN
1        Unadjusted            NaN
2        Unadjusted            NaN
3        Unadjusted            NaN
4        Unadjusted            NaN
...             ...            ...
5781          Trend            NaN
5782          Trend            NaN
5783          Trend            NaN
5784          Trend            NaN
5785          Trend            NaN

[5786 rows x 14 columns]

In [ ]:
df1=df.copy()

In [ ]:
df.head()

               Date;Open;High;Low;Close;Volume
0    2004.06.11 07:15;384;384.3;383.8;384.3;12
1  2004.06.11 07:30;383.8;384.3;383.6;383.8;12
2  2004.06.11 07:45;383.3;383.8;383.3;383.8;20
3   2004.06.11 08:00;383.8;384.1;383.6;383.6;8
4  2004.06.11 08:15;383.6;384.3;383.5;383.5;20

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 494235 entries, 0 to 494234
Data columns (total 1 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Date;Open;High;Low;Close;Volume  494235 non-null  object
dtypes: object(1)
memory usage: 3.8+ MB

In [ ]:
print(df1.columns.all)

<bound method Index.all of Index(['Series_reference', 'Period', 'Data_value', 'Suppressed', 'STATUS',
       'UNITS', 'Magnitude', 'Subject', 'Group', 'Series_title_1',
       'Series_title_2', 'Series_title_3', 'Series_title_4', 'Series_title_5'],
      dtype='object')>

In [ ]:
df1=df1.drop("Series_reference",axis = 1)

In [ ]:
print(df1)

       Period  Data_value  Suppressed STATUS    UNITS  Magnitude  \
0     1995.03    2368.690         NaN      F  Dollars          6
1     1995.06    2100.440         NaN      F  Dollars          6
2     1995.09    2070.210         NaN      F  Dollars          6
3     1995.12    2284.770         NaN      F  Dollars          6
4     1996.03    2134.760         NaN      F  Dollars          6
...       ...         ...         ...    ...      ...        ...
5781  2025.06   18026.490         NaN      R  Dollars          6
5782  2025.09   17885.529         NaN      R  Dollars          6
5783  2025.12   17842.642         NaN      R  Dollars          6
5784  2026.03   18406.127         NaN      R  Dollars          6
5785  2026.06   19255.759         NaN      F  Dollars          6

                           Subject  \
0     Wholesale Trade Survey - WTS
1     Wholesale Trade Survey - WTS
2     Wholesale Trade Survey - WTS
3     Wholesale Trade Survey - WTS
4     Wholesale Trade Survey - WTS
...                            ...
5781  Wholesale Trade Survey - WTS
5782  Wholesale Trade Survey - WTS
5783  Wholesale Trade Survey - WTS
5784  Wholesale Trade Survey - WTS
5785  Wholesale Trade Survey - WTS

                                                  Group  \
0     Industry by variable - (ANZSIC06) - Subannual ...
1     Industry by variable - (ANZSIC06) - Subannual ...
2     Industry by variable - (ANZSIC06) - Subannual ...
3     Industry by variable - (ANZSIC06) - Subannual ...
4     Industry by variable - (ANZSIC06) - Subannual ...
...                                                 ...
5781  Industry by variable - (ANZSIC06) - Subannual ...
5782  Industry by variable - (ANZSIC06) - Subannual ...
5783  Industry by variable - (ANZSIC06) - Subannual ...
5784  Industry by variable - (ANZSIC06) - Subannual ...
5785  Industry by variable - (ANZSIC06) - Subannual ...

                  Series_title_1            Series_title_2  Series_title_3  \
0     Basic material wholesaling  Sales (operating income)  Current prices
1     Basic material wholesaling  Sales (operating income)  Current prices
2     Basic material wholesaling  Sales (operating income)  Current prices
3     Basic material wholesaling  Sales (operating income)  Current prices
4     Basic material wholesaling  Sales (operating income)  Current prices
...                          ...                       ...             ...
5781           Total wholesaling              Total stocks  Current prices
5782           Total wholesaling              Total stocks  Current prices
5783           Total wholesaling              Total stocks  Current prices
5784           Total wholesaling              Total stocks  Current prices
5785           Total wholesaling              Total stocks  Current prices

     Series_title_4 Series_title_5
0        Unadjusted            NaN
1        Unadjusted            NaN
2        Unadjusted            NaN
3        Unadjusted            NaN
4        Unadjusted            NaN
...             ...            ...
5781          Trend            NaN
5782          Trend            NaN
5783          Trend            NaN
5784          Trend            NaN
5785          Trend            NaN

[5786 rows x 13 columns]

In [ ]:
df1=df1.dropna()

In [ ]:
print(df)

     Series_reference   Period  Data_value  Suppressed STATUS    UNITS  \
0         WTSQ.SFA1CA  1995.03    2368.690         NaN      F  Dollars
1         WTSQ.SFA1CA  1995.06    2100.440         NaN      F  Dollars
2         WTSQ.SFA1CA  1995.09    2070.210         NaN      F  Dollars
3         WTSQ.SFA1CA  1995.12    2284.770         NaN      F  Dollars
4         WTSQ.SFA1CA  1996.03    2134.760         NaN      F  Dollars
...               ...      ...         ...         ...    ...      ...
5781      WTSQ.SFZ9CT  2025.06   18026.490         NaN      R  Dollars
5782      WTSQ.SFZ9CT  2025.09   17885.529         NaN      R  Dollars
5783      WTSQ.SFZ9CT  2025.12   17842.642         NaN      R  Dollars
5784      WTSQ.SFZ9CT  2026.03   18406.127         NaN      R  Dollars
5785      WTSQ.SFZ9CT  2026.06   19255.759         NaN      F  Dollars

      Magnitude                       Subject  \
0             6  Wholesale Trade Survey - WTS
1             6  Wholesale Trade Survey - WTS
2             6  Wholesale Trade Survey - WTS
3             6  Wholesale Trade Survey - WTS
4             6  Wholesale Trade Survey - WTS
...         ...                           ...
5781          6  Wholesale Trade Survey - WTS
5782          6  Wholesale Trade Survey - WTS
5783          6  Wholesale Trade Survey - WTS
5784          6  Wholesale Trade Survey - WTS
5785          6  Wholesale Trade Survey - WTS

                                                  Group  \
0     Industry by variable - (ANZSIC06) - Subannual ...
1     Industry by variable - (ANZSIC06) - Subannual ...
2     Industry by variable - (ANZSIC06) - Subannual ...
3     Industry by variable - (ANZSIC06) - Subannual ...
4     Industry by variable - (ANZSIC06) - Subannual ...
...                                                 ...
5781  Industry by variable - (ANZSIC06) - Subannual ...
5782  Industry by variable - (ANZSIC06) - Subannual ...
5783  Industry by variable - (ANZSIC06) - Subannual ...
5784  Industry by variable - (ANZSIC06) - Subannual ...
5785  Industry by variable - (ANZSIC06) - Subannual ...

                  Series_title_1            Series_title_2  Series_title_3  \
0     Basic material wholesaling  Sales (operating income)  Current prices
1     Basic material wholesaling  Sales (operating income)  Current prices
2     Basic material wholesaling  Sales (operating income)  Current prices
3     Basic material wholesaling  Sales (operating income)  Current prices
4     Basic material wholesaling  Sales (operating income)  Current prices
...                          ...                       ...             ...
5781           Total wholesaling              Total stocks  Current prices
5782           Total wholesaling              Total stocks  Current prices
5783           Total wholesaling              Total stocks  Current prices
5784           Total wholesaling              Total stocks  Current prices
5785           Total wholesaling              Total stocks  Current prices

     Series_title_4 Series_title_5
0        Unadjusted            NaN
1        Unadjusted            NaN
2        Unadjusted            NaN
3        Unadjusted            NaN
4        Unadjusted            NaN
...             ...            ...
5781          Trend            NaN
5782          Trend            NaN
5783          Trend            NaN
5784          Trend            NaN
5785          Trend            NaN

[5786 rows x 14 columns]

In [ ]:
df.head()

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,WTSQ.SFA1CA,1995.03,2368.69,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
1,WTSQ.SFA1CA,1995.06,2100.44,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
2,WTSQ.SFA1CA,1995.09,2070.21,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
3,WTSQ.SFA1CA,1995.12,2284.77,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
4,WTSQ.SFA1CA,1996.03,2134.76,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN

In [ ]:
df1.head()

Empty DataFrame
Columns: [Period, Data_value, Suppressed, STATUS, UNITS, Magnitude, Subject, Group, Series_title_1, Series_title_2, Series_title_3, Series_title_4, Series_title_5]
Index: []

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df.head()

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,WTSQ.SFA1CA,1995.03,2368.69,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
1,WTSQ.SFA1CA,1995.06,2100.44,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
2,WTSQ.SFA1CA,1995.09,2070.21,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
3,WTSQ.SFA1CA,1995.12,2284.77,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN
4,WTSQ.SFA1CA,1996.03,2134.76,NaN,F,Dollars,6,Wholesale Trade Survey - WTS,Industry by variable - (ANZSIC06) - Subannual ...,Basic material wholesaling,Sales (operating income),Current prices,Unadjusted,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5786 entries, 0 to 5785
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Series_reference  5786 non-null   object
 1   Period            5786 non-null   float64
 2   Data_value        5786 non-null   float64
 3   Suppressed        0 non-null      float64
 4   STATUS            5786 non-null   object
 5   UNITS             5786 non-null   object
 6   Magnitude         5786 non-null   int64
 7   Subject           5786 non-null   object
 8   Group             5786 non-null   object
 9   Series_title_1    5786 non-null   object
 10  Series_title_2    5786 non-null   object
 11  Series_title_3    5786 non-null   object
 12  Series_title_4    5786 non-null   object
 13  Series_title_5    494 non-null    object
dtypes: float64(3), int64(1), object(10)
memory usage: 633.0+ KB

In [ ]:
df["Series_reference"]=pd.to_datetime(df["Series_reference"])

/tmp/ipykernel_1771/4067188346.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Series_reference"]=pd.to_datetime(df["Series_reference"])

DateParseError: Unknown datetime string format, unable to parse: WTSQ.SFA1CA, at position 0